-- Права на схему public
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO svcm;

-- Схема core
CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION svcm;
COMMENT ON SCHEMA core IS 'Основные бизнес-объекты системы';
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA core GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA core GRANT SELECT, USAGE ON SEQUENCES TO svcm;

-- Схема sys
CREATE SCHEMA IF NOT EXISTS sys AUTHORIZATION svcm;
COMMENT ON SCHEMA sys IS 'Хранение данных о пользователях, ролях, функциях сервиса, правах доступа, а так же логи работы пользователя';
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA sys GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA sys GRANT SELECT, USAGE ON SEQUENCES TO svcm;

-- Схема stream
CREATE SCHEMA IF NOT EXISTS stream AUTHORIZATION svcm;
COMMENT ON SCHEMA stream IS 'Организация распределенного обмена данными и интеграцией';
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA stream GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA stream GRANT SELECT, USAGE ON SEQUENCES TO svcm;

