CREATE ROLE svcm NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
ALTER ROLE svcm WITH ENCRYPTED PASSWORD 'need_to_be_better';
GRANT CONNECT ON DATABASE ta TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svcm;
ALTER DEFAULT PRIVILEGES FOR ROLE svcm IN SCHEMA public
      GRANT SELECT, USAGE ON SEQUENCES TO svcm;
